name: Generate GitHub Stats

on:
  schedule: # Ejecuta cada 12 horas
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download GitHub stats images
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          mkdir -p dist
          # Stats de commits y contribuciones privadas
          curl -H "Authorization: token $GH_TOKEN" \
            "https://github-readme-stats.vercel.app/api?username=rauuul-dev&count_private=true&theme=dracula&hide_border=false" \
            -o dist/stats.svg

          # Stats de lenguajes principales
          curl -H "Authorization: token $GH_TOKEN" \
            "https://github-readme-stats.vercel.app/api/top-langs?username=rauuul-dev&layout=compact&langs_count=5&theme=dracula&hide_border=false" \
            -o dist/languages.svg

      - name: Push stats to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
